sys.app-name=mail-0.0.1
server.port=8096
spring.datasource.url=jdbc:pgsql://fenomy.cc:5432/fenomy
spring.datasource.driver-class-name=com.impossibl.postgres.jdbc.PGDriver
spring.datasource.username=kernel
spring.datasource.password=kernel

spring.mail.host=smtp.fenomy.com
spring.mail.port=587
spring.mail.username=info@fenomy.com
spring.mail.password=8fT2cgT8tsBDZ5sj
spring.mail.sender.email=info@fenomy.com
spring.mail.sender.text=INFO

spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp

#spring.datasource.url=jdbc:postgresql://fenomy.cc:5432/fenomy
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.com.zaxxer.hikari=warn
logging.level.com.anksystems=debug
logging.level.com.anksystems.fenomy_sys.FenomySysApplication=debug
logging.level.com.anksystems.fenomy_sys.FenomySysApplicationKt=debug
logging.file.name=build/tmp/${sys.app-name}.log

